version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - '/'
      - '/packages'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 2
    groups:
      dependencies:
        dependency-type: 'production'
      devDependencies:
        dependency-type: 'development'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 1
    groups:
      actions:
        patterns:
          - '*'
    cooldown:
      default-days: 14
